version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2345:80'
        volumes:
            - ./src:/var/www/html

    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: password
        volumes:
            # Pour lancer un dump automatiquement au montage du conteneur
            - ./etc/database.sql:/docker-entrypoint-initdb.d/dump.sql
            - db_data:/var/lib/mysql


    adminer:
        image: adminer
        restart: always
        ports:
            - '2346:8080'
        environment:
            - PMA_ARBITRARY=1
    
volumes:
    db_data: